export enum ApiRoutes {
  USER = '/users',
  AUTHENTICATION = '/auth',
  PRODUCTS = '/products',
  CATEGORY = '/category',
  CONTROL_PANEL = '/control-panel',
  SELLER_PRODUCTS = '/seller',
  SELLER_INFO = '/seller/info',
  SELLER_FEEDBACKS = '/feedback/comments',
  PRODUCT_RATINGS = '/feedback/product',
  PRODUCT_COMMENTS = '/feedback/comments/product',
  RATINGS = '/feedback/seller',
  SUPPORT = '/support',
  WISHLIST = '/wishlist',
}
